### ISSUE TITLE
Allow for css configuration of mermaid

### ISSUE THREAD

**Issue by agusmba** [mermaidjs/mermaid.cli#12]
Right now the css is hardcoded in mermaid.cli.
It would be nice to be able to indicate a local css to take precedence and thus modify the resulting images.

I will try to propose something.

**Comment by agusmba** [comment]
Fix has been merged.

**Comment by kellerj** [comment]
This does not seem to be working properly.  It does seem that the CSS is getting pulled in somewhere in the process as fonts and spacing changes.  But then it is not included in the in-memory HTML page used for rendering, so most of the formatting does not take effect.

**Comment by agusmba** [comment]
Do you have a simple non-working example?

If I write in the repository:

```
$ node index.bundle.js -w 2000 -i test/sequence.mmd -o test2000.png -C test/testCSS.css
```

I get:
![test2000](https://user-images.githubusercontent.com/3104020/32464546-b0c45ffc-c340-11e7-812c-072bc5aa2c58.png)

(If you don't have Exo 2 installed locally you might see a different font)

**Comment by kellerj** [comment]
I can create one - may take a day or so to get the time.  But the problem seems to be in the colors and line styles mainly.  I'm not sure why the font items work.  (But those were inconsistent between the PNG and SVG output.)

I did put in a new issue with a linked PR (#17) which has the patch that fixed this issue for me.  But, depending on how you intended that CSS file to be used.  (Mine was a full altered copy of the default mermaid.css file.)

**Comment by tylerlong** [comment]
Please refer to https://github.com/mermaidjs/mermaid.cli/pull/24#issuecomment-373402785

**Comment by tylerlong** [comment]
The document of mermaid is quite dated. We need to update it.
