### ISSUE TITLE
libraryize & wrap CLI around library

### ISSUE THREAD

**Issue by konsumer** [mermaidjs/mermaid.cli#22]
I think it'd be neat to programmatically use mermaid, in node. Maybe call it "mermaid-serverside".

I'd like to make an img-url parser, so you can inline the source of the graph in the URL and get an image. It would also mean that I can pre-render graphs, so there is no flash of graph-source on pages (I made a [gatsby plugin](https://github.com/konsumer/gatsby-remark-graph), for example, that has some hacks to make it work browser-only, but I'd prefer they were pre-built.)

If we had this, it'd be really simple to just wrap the CLI around that bit. If there is interest, I'd be happy to write it, and make a PR for this project to use the lib.

**Comment by tylerlong** [comment]
> I think it'd be neat to programmatically use mermaid, in node. Maybe call it "mermaid-serverside".

The idea of mermaid-serverside is cool. However, mermaid currently cannot work without a browser (either a normal browser or a headless browser such as puppeteer). So mermaid could not be a pure node.js library (which doesn't depend on browsers)

 > I'd like to make an img-url parser, so you can inline the source of the graph in the URL and get an image. 

We have something similar: https://mermaidjs.github.io/mermaid-live-editor/#/view/Z3JhcGggVEQKQVtDaHJpc3RtYXNdIC0tPnxHZXQgbW9uZXl8IEIoR28gc2hvcHBpbmcpCkIgLS0-IEN7TGV0IG1lIHRoaW5rfQpDIC0tPnxPbmV8IERbTGFwdG9wXQpDIC0tPnxUd298IEVbaVBob25lXQpDIC0tPnxUaHJlZXwgRltDYXJdCg


> It would also mean that I can pre-render graphs, so there is no flash of graph-source on pages (I made a gatsby plugin, for example, that has some hacks to make it work browser-only, but I'd prefer they were pre-built.)

As I said above, pre-render without a browser is currently impossible.  But if you know how to make it possible, that would be super great! I used to try jsdom but failed.

> If we had this, it'd be really simple to just wrap the CLI around that bit. If there is interest, I'd be happy to write it, and make a PR for this project to use the lib.

I don't know if this is helpful. Because this library needs a browser to work. So there is no pre-render in memory only. And it is not a pure node library which doesn't depend on browsers.

Please feel free to post more comments. I will leave this issue open for now.

**Comment by konsumer** [comment]
> We have something similar:

That's cool, but I meant like this, with source inline in image-link, so you can use it directly:

![image](https://gravizo.com/svg?@startuml;actor%20User;participant%20%22First%20Class%22%20as%20A;participant%20%22Second%20Class%22%20as%20B;participant%20%22Last%20Class%22%20as%20C;User%20-%3E%20A:%20DoWork;activate%20A;A%20-%3E%20B:%20Create%20Request;activate%20B;B%20-%3E%20C:%20DoWork;activate%20C;C%20--%3E%20B:%20WorkDone;destroy%20C;B%20--%3E%20A:%20Request%20Created;deactivate%20B;A%20--%3E%20User:%20Done;deactivate%20A;@enduml)

> As I said above, pre-render without a browser is currently impossible

Yeh, I get that, but I mean in the same way you use puppeteer to create a chrome-headless client, render it, and return it. I dunno, maybe it makes no sense to integrate with this. The CLI is pretty light, maybe I should just make a separate library that works the same way, based on your great work. At some point, if I get a wild hair, maybe I'll do some realy node-space rendering though, as mermaid uses d3, and there is a [node d3](https://www.npmjs.com/package/d3-node).

**Comment by tylerlong** [comment]
It will be super cool if you can make mermaid a pure node.js library. Actually I think it is possible, just more investigation is needed.

**Comment by konsumer** [comment]
Yep, totally agreed. I think it's very close with [node-d3](https://www.npmjs.com/package/d3-node), but in the interim, I could wrap puppeteer, as you have, to make a server-side renderer (which was my original thought.)

If I have some time, I will investigate this week, and see what it would take to make it render in [node-d3](https://www.npmjs.com/package/d3-node). If nothing else, it'd give us a list to work through for things needed to support that.

**Comment by GARENFEATHER** [comment]
@konsumer If you dont mind, Any solution now？

_Sent from my PRO 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by tylerlong** [comment]
Please read this thread: https://github.com/knsv/mermaid/issues/559

I will close it for now.
