### ISSUE TITLE
Exit on failure

### ISSUE THREAD

**Issue by z-george-ma** [mermaidjs/mermaid.cli#41]
**Description**
mmdc doesn't exit when input file is invalid. It is probably okay for interactive user session, but makes it harder to use for any automation usage.

**Example**
```
gantt
   dateFormat  YYYY-MM-DD

abc
```

**Expect**
mmdc exits with non-zero exit code

**Actual**
mmdc hangs with the following output, and user has to press ctrl-c to exit
```
(node:7583) UnhandledPromiseRejectionWarning: Error: Evaluation failed: Error: Parse error on line 4:
...mat  YYYY-MM-DDabc
...
```

**Comment by pturley** [comment]
I agree, this would be really nice to have

**Comment by hasanalrasyid** [comment]
Is this behavior coming from the main node.js?
The error said
"(node:7014) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code."

Really wished for that not so far future to come soon...

**Comment by prantlf** [comment]
The main program body is asynchronous, but it does not handle errors thrown during the graph processing. Such errors are (still) handled by Node.js, but his approach is not recommended, hence the warnings printed by Node.js. The process hangs, because there are still callbacks waiting. (Chrome is running.)

I created PR #66 to fix this problem by terminating the process with a non-zero exit code.

**Comment by aloisklink** [comment]
Development has moved to the https://github.com/mermaid-js/mermaid-cli repo, please re-open your issue there if it's still relevant.
The package has also been renamed on NPM to [`@mermaid-js/mermaid-cli`](https://www.npmjs.com/package/@mermaid-js/mermaid-cli), so you may need to run `npm uninstall mermaid.cli && npm install @mermaid-js/mermaid-cli` to get the latest version of this package.

FYI, I'm pretty sure that this has been fixed by https://github.com/mermaid-js/mermaid-cli/pull/321 in `@mermaid-js/mermaid-cli`, thanks to some changes to the core Mermaid API!
