### ISSUE TITLE
Is really necessary to have chromium ?

### ISSUE THREAD

**Issue by Zikoel** [mermaidjs/mermaid.cli#42]
Hi,
I am included mermaid and mermaid.cli inside my CI platform. Every time someone push on master a new clone of the project is place on a workdir and `npm install` is performed. Now every time more that 100MB was downloaded for chromium that is not used... why coupling a small tool like this to a big bundle like chromium? There is way to avoid it?

**Comment by dotancohen** [comment]
In fact Mermaid can be so small because it uses major Chromium components.

You might be interested in the Mermaid sister project Ariel, which is very similar to Mermaid but does not rely on Chromium:
https://github.com/mermaidjs/ariel-diagrams

As this "issue" is not a bug or feature request, of course it should be closed. That said, it would be nice if the dev who closes this issue could add a link to a forum where questions like this are appropriate. I see that Stack Overflow has a `mermaid` tag, but is there a better place?
https://stackoverflow.com/questions/tagged/mermaid

**Comment by psibernetic** [comment]
@Zikoel You might look at standing up an API next to your CI instead, that is why I built [mermaidfunc](https://github.com/psibernetic/mermaidfunc)

**Comment by paul-hammant** [comment]
Update README to say why Mermaid requires puppeteer and Chromium. Sure, insiders know why to people from the user community like me, it's a legitimate self-preservation questions: why does something that makes PNGs pr SVGs need to automate a browser, and why's that not discussed in the README?
