### ISSUE TITLE
Background option doesn't work with svg

### ISSUE THREAD

**Issue by Jmuccigr** [mermaidjs/mermaid.cli#43]
the `-b <color>` option works fine with png and pdf, but not with svg where the output always has a white background.

Version 0.5.1 on a Mac 10.13.5

**Comment by mr-nigiri** [comment]
Same behavior on linux inside docker (alekzonder/puppeteer)

**Comment by lorenzznerol** [comment]
You made the same mistake as probably many others. I also just took the install command from [the npm site](https://www.npmjs.com/package/mermaid.cli) which is as outdated as the [outdated old repo](https://github.com/mermaidjs/mermaid.cli/). 

Install from the [new repo](https://github.com/mermaid-js/mermaid-cli)

```bash
yarn add @mermaid-js/mermaid-cli
./node_modules/.bin/mmdc -h
```

Or use NPM:

```bash
npm install @mermaid-js/mermaid-cli
./node_modules/.bin/mmdc -h
```

**Comment by aloisklink** [comment]
Development has moved to the https://github.com/mermaid-js/mermaid-cli repo, please re-open your issue there if it's still relevant.
The package has also been renamed on NPM to [`@mermaid-js/mermaid-cli`](https://www.npmjs.com/package/@mermaid-js/mermaid-cli), so you may need to run `npm uninstall mermaid.cli && npm install @mermaid-js/mermaid-cli` to get the latest version of this package.

I believe this has been fixed by https://github.com/mermaid-js/mermaid-cli/pull/214 in `@mermaid-js/mermaid-cli`.
