### ISSUE TITLE
Question - How to change flowchart width?

### ISSUE THREAD

**Issue by venki09** [mermaidjs/mermaid.cli#61]
Whats the best way to change the width of flowchart being rendered? I tried to specify the width property via `-w` but doesn't look like they were being honored. 

```
mmdc -i sample.mmd -o output.png -w 1500
```

I also tried to specify it in the json config file and that didn't work too
```
{
  "flowchart": {
    "width": "1500"
  }
}
```

Am I missing something really trivial here? Please help me out. Thanks in advance!

**Comment by aloisklink** [comment]
Development has moved to the https://github.com/mermaid-js/mermaid-cli repo, please re-open your issue there if it's still relevant.
The package has also been renamed on NPM to [`@mermaid-js/mermaid-cli`](https://www.npmjs.com/package/@mermaid-js/mermaid-cli), so you may need to run `npm uninstall mermaid.cli && npm install @mermaid-js/mermaid-cli` to get the latest version of this package.

You might also need to set

```
{
    "flowchart": {
        "useMaxWidth": true
    },
}
```

in your Mermaid config, since Mermaid v9.1.7 changed this behavior in https://github.com/mermaid-js/mermaid/commit/2968b400c49f66983e6d206959504e72aa6ae0ef
