### ISSUE TITLE
What's the difference between mermaidjs and mermaid-js?

### ISSUE THREAD

**Issue by hyperh** [mermaidjs/mermaid.cli#75]
https://github.com/mermaid-js/mermaid.cli and https://github.com/mermaidjs/mermaid.cli both exist.

I can see `mermaid-js/mermaid.cli` was forked from here. `mermaid.cli` on [npm](https://www.npmjs.com/package/mermaid.cli) points to this repo. But the npm package hasn't been updated in 2 years. I don't really get what the difference between `mermaidjs` and `mermaid-js` is. The hyphen one seems to be the core package (i.e. `npm install mermaid`)?

**Comment by hannahhoward** [comment]
I do not know but my guess is that this repo has stalled and the mermaid maintainers are taking it over but haven't pushed a release yet.

mermaid-js is the official home for mermaid itself.

**Comment by hannahhoward** [comment]
this is my way of saying +1 cause now the docs are different from what you get if you use mermaid.cli -- for example, the sequence diagram backgrounds do not work cause the mermaid version in this repo is out of date.

**Comment by aloisklink** [comment]
Development has moved to the https://github.com/mermaid-js/mermaid-cli repo, please re-open your issue there if it's still relevant.
The package has also been renamed on NPM to [`@mermaid-js/mermaid-cli`](https://www.npmjs.com/package/@mermaid-js/mermaid-cli), so you may need to run `npm uninstall mermaid.cli && npm install @mermaid-js/mermaid-cli` to get the latest version of this package.

> I do not know but my guess is that this repo has stalled and the mermaid maintainers are taking it over but haven't pushed a release yet.

Pretty much :) The `@mermaid-js/mermaid-cli` has been maintained for the last few years, unlike this repo (I think due to permissions issues).

I've recently managed to get admin permissions for this old repo though, so I'm closing all the issues/PRs and I'm going to [archive it](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories), so that everybody knows to go to the new repo.
